name: 'PR Title Check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    name: PR Title Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form fix(AAiT-backend-1A): Update Login Page
          pattern: '^[a-z]*\((AASTU|AAiT)-(web|backend|mobile)-(1|2|3|4|1A|1B|2A|2B)\):.*'
